spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://dbpostgres:5432/mahasiswaservice_db
      username: postgres
      password: password
  application:
    name: mahasiswa-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8081